# Generated by Django 5.2.8 on 2025-11-19 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='masked_account',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('gcash', 'GCash'), ('card', 'Card')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='ticket_ref',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
