# Generated by Django 5.2.8 on 2025-11-21 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_reservation_is_paid_reservation_masked_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showtime',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='seat',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='showtime',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
        migrations.DeleteModel(
            name='Showtime',
        ),
    ]
